### ISSUE TITLE
new Syllabus

### ISSUE THREAD

**Issue by dwu300** [BPMspaceUG/SQMS2#4]
## before create
* Version should be hidden
* Description Text in any Language existing should be shown

## after created:
* Show Relations to Topics but not active

## General
* Create Tests with PHPUnit
* And also Testing via Selenium IDE
* convert GUI_ID prefix to prefixID
* Automatically set Tables in Statemachine (virtualTables)
* SET Auto_increment Offset at generating

--------------
# Exam Set Version
* Sample Set hidden im created

**Comment by BPMspace** [comment]
Scenario Outline: Creating a new multilanguage Syllabus
    Given I am logged in
    When I go to the page Syllabus
    And click on the create button 
	Then the form with 3 input fields appears
    And I am entering
					text in a field Title
					select Date in a date picker from when the Syllabus is valid
					select Date in a date picker until when the Syllabus is valid
	When I click on the create button				
	Then the Syllabus is saved in status new

**Comment by AnaMickovic** [comment]
DO Not CREATE and present Messages since only one SD per language for a syllabus shall be accepted ( to confirm the request - Rob?)
